### PR TITLE
feat!: Revert deprecating retrieve_token, adding support of environment variables

### LINKED ISSUE #39: Trying to retrieve token from Keyring causes an error on WSL2
Although WSL provides a lot of features available in Linux, dbus is not well-supported (https://github.com/microsoft/WSL/issues/8842) and causes the following error:
```
ERROR Secure storage error: Secret Service returned an error: no secret service provider or dbus session found
```
 and even if you work-around it (by logging into wsl with `wsl.exe -u root -- su <USER> `) and created the proper dbus, there will be another error:
```
ERROR Secure storage error: Secret Service returned an error: zbus error: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

Currently gh-config's implementation returns Err when Keyring returns an error as `self.retrieve_token_secure(hostname)?`, but I would personally like gh-config to fall back to retrieving tokens naively from yaml files. I'm not sure how to properly handle this error so I'd appreciate thoughts over this issue. Maybe returning Ok(None) when Keyring fails connecting to dbus or fails to find a service?

https://github.com/siketyan/gh-config-rs/blob/a8157c066c76de7420110cf5761d4d81cc6bb824/src/lib.rs#L172-L184

### PR DESCRIPTION
**Pull request by siketyan**
Closes #39 

Removing the deprecation that was introduced in #11.
Also adding support of environment variables: `GH_ENTERPRISE_TOKEN`, `GITHUB_ENTERPRISE_TOKEN`, `GH_TOKEN`, and `GITHUB_TOKEN`. It will be preferred than the token from hosts.yaml file or the secure storage.

### CODE REVIEW

**Comment by siketyan** [comment]
Will be shipped in 0.4.0 as this PR contains some breaking changes.

**Comment by s3i7h** [comment]
Looks good! I was implementing this feature myself, and took a different approach for separating different methods of retrieving tokens. could you take a look of mine and tell me what you think? 

https://github.com/siketyan/gh-config-rs/compare/GH-39...s3i7h:gh-config-rs:feat/brush-up-token-handling?expand=1

Though after reading go-gh I found my implementations are not correct about handling enterprise tokens, so treat my code like a pseudo code.  e.g. the order of resolution is actually enterprise env > enterprise config > gh env > gh config (last config look up is a no-op because it's the same as the one before) so maybe combining retrieve_token_from_env and retrieve_token_from_config might be a way etc.
 https://github.com/cli/go-gh/blob/dbd982eba2a041d88d398cce01cb708c4c3503f7/pkg/auth/auth.go#L63

**Comment by siketyan** [comment]
@s3i7h Noticed my implementation does not handle them correctly too. However I would not like to combine loading from environment variables and loading from the hosts.yaml file tbh. Also gh-config-rs never have no grantee for the consistency with go-gh. Thus I would like to keep the order of GH_ENTERPRISE_TOKEN, GITHUB_ENTERPRISE_TOKEN > GH_TOKEN, GITHUB_TOKEN > hosts.yaml > secure storage. Any thoughts about this?

**Comment by s3i7h** [comment]
I too think that order will be more concise (as it can completely  isolate interactions with envs and config)

The only case this implementation breaks behavior is when yml has the specified host's token but (GITHUB|GH)_TOKEN is also present, and IMO both implementations favoring each other makes sense, so I think we can make it a decision to go with the implementation you suggested 👍

I still prefer to separate each retrieve_token_from_* functions and iterate them inside retrieve_token though

**Comment by siketyan** [comment]
I decided that keeping the current implementation in this branch as each functions has reusability themselves without depending on impls on the Hosts struct. The Hosts struct should be loaded only if we need to access `~/.config/gh/hosts.yml`.

Thank you for your review and idea anyway!

**Comment by s3i7h** [comment]
@siketyan hmm, so are you suggesting to separate token handling from Hosts struct entirely?

I support the decision but won't it involve a lot of breaking changes? If so, I'd prefer to implement the decisions we made above as Hosts impl for the time being, and make the migration a different issue. What do you think? I can put my hands on either of it :)

**Comment by s3i7h** [comment]
@siketyan ping ↑

**Comment by siketyan** [comment]
@s3i7h No, `retrieve_token` method itself will remain in the impl of `Hosts` struct (at least for now). However `retrieve_token_from_env` and `retrieve_token_secure` functions are placed on top-level as loading `Hosts` can be omitted while reading token from environment variables or from the secure storage. As the diff shows, `retrieve_token_secure` method in `Hosts` struct is an only thing that will be a breaking change in this changes.

**Comment by s3i7h** [comment]
Ah I somehow overlooked the actual changes. Makes sense and looks good to me now 😌 sorry for taking up your time

**Pull request merged**
